version: "3.4"

services: 
  web-server: 
    container_name: main-api 
    build: 
      context: .
    ports: 
      - 8080:8080
  
  web-server-cache: 
    container_name: redis-cache 
    image: redis:7.2-alpine
    restart: always
    ports: 
      - "6379:6379"
    volumes: 
      - /beef/cache-go-api/data:/var/lib/redis/data
    # environment: 
    #   - REDIS_PASSWORD=my-password 
    #   - REDIS_PORT=6379
    #   - REDIS_DATABASES=16